# This is a basic workflow to help you get started with Actions

name: Generator

on:
  push:
    paths:
    - 'scripts/templates/**'
    - 'scripts/gen_module.sh'
    - '.github/workflows/generator.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TF_VAR_sfx_token: ${{ secrets.SFX_TOKEN }}
      TF_VAR_pagerduty_integration_id: ${{ secrets.PAGERDUTY_INTEGRATION }}
      TF_VAR_environment: "ci-testing"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.0
      with:
        terraform_version: 0.13.3
        terraform_wrapper: false

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install j2cli[yaml]

    - name: Setup env
      run: |
        ./scripts/gen_module.sh ${TF_VAR_environment} module
        for config in scripts/templates/threshold/*.yaml; do 
          j2 <(cat scripts/templates/detector_vars.tf.j2 scripts/templates/detector_res.tf.j2) $config >> modules/${TF_VAR_environment}-module/gen.tf
        done
        echo -e "module \"generated\" {\nsource=\"../modules/${TF_VAR_environment}-module\"\n$(cat common/modules-args.txt)\n}" >> test/gen.tf
    
    - name: Terraform fmt
      run: terraform fmt -write=false -diff -check modules/${TF_VAR_environment}-module

    - name: Terraform init
      run: terraform init test

    - name: Terraform validate
      run: terraform validate test

    - name: Enable destroy
      run: echo ::set-output name=enabled::1
      id: destroy

    - name: Terraform Apply
      run: echo yes | terraform apply -input=false -lock=false test

    - name: Terraform Destroy
      if: always() && steps.destroy.outputs.enabled == '1'
      run: terraform destroy -input=false -lock=false -auto-approve test

