# This is a basic workflow to help you get started with Actions

name: Detectors

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
    - '**.tf'
    - 'scripts/*'
    - '.github/workflows/main.yml'
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deployment:
    # The type of runner that the job will run on
    #runs-on: hashicorp/terraform:full
    runs-on: ubuntu-latest
    container:
      image: "claranet/terraform-ci:latest"
    env:
      TF_VAR_sfx_token: ${{ secrets.SFX_TOKEN }}
      TF_VAR_pagerduty_integration_id: ${{ secrets.PAGERDUTY_INTEGRATION }}
      TF_VAR_environment: "ci-testing"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: 0.13.3
        terraform_wrapper: false

    - name: Setup env
      run: |
        TF_REF=$(git rev-parse HEAD)
        #TF_REF=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; NF>1{print $NF}')
        ./scripts/gen_tf.sh "${TF_REF}" > test/${TF_REF}.tf
        cat test/${TF_REF}.tf
    
    #- name: Terraform version
    #  run: terraform version

    - name: Terraform fmt
      run: terraform fmt -recursive -write=false -diff -check .

    - name: Terraform init
      run: terraform init test

    - name: Terraform validate
      run: terraform validate test

    #- name: Terraform Plan
    #  run: terraform plan -input=false -lock=false -detailed-exitcode test || if [ $? -ne 2 ]; then exit $?; fi

    - name: Enable destroy
      run: echo ::set-output name=enabled::1
      id: destroy

    - name: Terraform Apply
      #if: github.ref == 'refs/heads/master' && github.event_name == 'push' && ${{ always() }}
      run: terraform apply -input=false -lock=false -auto-approve test

    - name: Terraform Destroy
      if: always() && steps.destroy.outputs.enabled == '1'
      run: terraform destroy -input=false -lock=false -auto-approve test

  compliance:
    runs-on: ubuntu-latest
    container:
      image: "claranet/terraform-ci:0.13.3"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: apk add --no-cache expect

    - name: Run tflint
      run: ./scripts/lint_tf.sh

  outputs:
    runs-on: ubuntu-latest
    container:
      image: "claranet/terraform-ci:0.13.3"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate modules outputs
      run: ./scripts/gen_outputs.sh

    - name: Check for changes
      run: git diff --exit-code

